version: '3.8'
services:
  diagnostics_explorer:
    image: ohdsi/uveitis_safetey_estimation_app:1.0.0
    build:
      context: .
      args:
         APP_NAME: uveitis_safety_estimation
    ports:
      - "3838:3838"

